### ISSUE TITLE
Strider 500 on two hop (Workflow D)

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#222]
Query:
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01"
                },
                "e01": {
                    "subject": "n01",
                    "object": "n02"
                }
            },
            "nodes": {
                "n00": {
                    "ids": [
                        "DOID:14330"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:NamedThing"
                    ]
                },
                "n02": {
                    "ids": [
                        "DOID:8778"
                    ],
                    "categories": [
                        "biolink:Disease"
                    ]
                }
            }
        }
    }
}
```

Strider result:
```
<function strider at 0x7fa70fa96700> error: 500
{'message': {}, 'logs': [{'message': "Exception in Strider: ReadTimeout('')", 'level': 'ERROR', 'timestamp': '2021-07-08T14:32:20.095739', 'stack': 'Traceback (most recent call last):\n  File "/app/./strider/server.py", line 94, in catch_exceptions_middleware\n    return await call_next(request)\n  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next\n    task.result()\n  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro\n    await self.app(scope, receive, send)\n  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__\n    await self.app(scope, receive, send)\n  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__\n    raise exc from None\n  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__\n    await self.app(scope, receive, sender)\n  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__\n    await route.handle(scope, receive, send)\n  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle\n    await self.app(scope, receive, send)\n  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app\n    response = await func(request)\n  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 214, in app\n    raw_response = await run_endpoint_function(\n  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 149, in run_endpoint_function\n    return await dependant.call(**values)\n  File "/app/./strider/server.py", line 274, in sync_query\n    query_results = await process_query(qid, log_level, redis_client)\n  File "/app/./strider/server.py", line 188, in process_query\n    await strider.generate_plan()\n  File "/app/./strider/fetcher.py", line 163, in generate_plan\n    response = await client.get(url)\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1722, in get\n    return await self.request(\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1481, in request\n    response = await self.send(\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1568, in send\n    response = await self._send_handling_auth(\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1604, in _send_handling_auth\n    response = await self._send_handling_redirects(\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1640, in _send_handling_redirects\n    response = await self._send_single_request(request, timeout)\n  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1681, in _send_single_request\n    ) = await transport.handle_async_request(\n  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 278, in handle_async_request\n    (\n  File "/usr/local/lib/python3.9/contextlib.py", line 135, in __exit__\n    self.gen.throw(type, value, traceback)\n  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions\n    raise mapped_exc(message) from exc\nhttpx.ReadTimeout\n'}]}
```

Maybe some KP is timing out and strider is not handling it well?

**Comment by mmersmann** [comment]
**Next Step:** Patrick's batching work.

**Comment by mmersmann** [comment]
Abrar not getting a 500 error, instead getting an empty 200 response. @cbizon to re-try.

**Comment by cbizon** [comment]
Oops, well, I changed ChemicalSubstance to ChemicalEntity to be 2.1 compliant and strider never returned...

Also it generated a bunch of blocks like this one after another in the logs
```
Future exception was never retrieved
future: <Future finished exception=BrokenResourceError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 60, in read
    return await self.stream.receive(n)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/tls.py", line 152, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/tls.py", line 109, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1095, in receive
    raise self._protocol.exception
anyio.BrokenResourceError
```

**Comment by patrickkwang** [comment]
@cbizon What query did you send, exactly?

**Comment by cbizon** [comment]
```
{"message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        },
        "e01": {
          "object": "n02",
          "subject": "n01"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:ChemicalEntity"
          ],
          "ids": [
            "DRUGBANK:DB00215",
            "DRUGBANK:DB01175",
            "DRUGBANK:DB00472",
            "DRUGBANK:DB00176",
            "DRUGBANK:DB00715",
            "DRUGBANK:DB01104"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n02": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:114"
          ]
        }
      }
    }
  }
        }
```

**Comment by uhbrar** [comment]
I'm not getting a 500 error from Strider. Strider returns a 200, but there are a ton of 405 errors within the logs. Also, this query take a really long time to process, at least for me. Even on the speedup branch, it takes in excess of 15 minutes.

**Comment by mmersmann** [comment]
As of yesterday, Chris not getting 500 error, but getting closed connections. @cbizon to test using "provided by" queries.

**Comment by patrickkwang** [comment]
This is currently causing a 502 Bad Gateway in deployment. It completes with results on a local instance.

**Comment by cbizon** [comment]
Confirmed that it 502's in deployment.  Not sure what's up.  It fails in about 140 seconds.  @YaphetKG ?

**Comment by cbizon** [comment]
I don't see any of those funky errors in the logs, though it's a bit hard to tell b/c there are multiple pods

**Comment by cbizon** [comment]
Hmmm ... I got a 200 running it again, but response.json() is throwing because the json response is truncated

**Comment by YaphetKG** [comment]
the liveliness probes were too short (10s) we have increased those just now to 30s, and 502's I think would be fixed by this

**Comment by cbizon** [comment]
OK, seems to be returning with results now.
