### ISSUE TITLE
Crash with certain query.

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/strider#354]
The enclosed query seems to crash Strider (enclosed), versio ghcr.io/ranking-agent/strider:v3.17.0. 

Here is the stack trace:

2022-02-10T09:54:16-05:00 Traceback (most recent call last):
2022-02-10T09:54:16-05:00   File "/app/./strider/trapi_throttle/throttle.py", line 44, in wrapper
2022-02-10T09:54:16-05:00     return await fcn(*args, **kwargs)
2022-02-10T09:54:16-05:00   File "/app/./strider/trapi_throttle/throttle.py", line 288, in process_batch
2022-02-10T09:54:16-05:00     filtered_msg = filter_by_curie_mapping(
2022-02-10T09:54:16-05:00   File "/app/./strider/trapi_throttle/trapi.py", line 98, in filter_by_curie_mapping
2022-02-10T09:54:16-05:00     filtered_msg.kgraph = KnowledgeGraph(
2022-02-10T09:54:16-05:00   File "pydantic/main.py", line 422, in pydantic.main.BaseModel.__setattr__
2022-02-10T09:54:16-05:00 ValueError: "Message" object has no field "kgraph"
2022-02-10T09:54:24-05:00 Traceback (most recent call last):
2022-02-10T09:54:24-05:00   File "/app/./strider/trapi_throttle/throttle.py", line 44, in wrapper
2022-02-10T09:54:24-05:00     return await fcn(*args, **kwargs)
2022-02-10T09:54:24-05:00   File "/app/./strider/trapi_throttle/throttle.py", line 288, in process_batch
2022-02-10T09:54:24-05:00     filtered_msg = filter_by_curie_mapping(
2022-02-10T09:54:24-05:00   File "/app/./strider/trapi_throttle/trapi.py", line 99, in filter_by_curie_mapping
2022-02-10T09:54:24-05:00     nodes={
2022-02-10T09:54:24-05:00   File "/app/./strider/trapi_throttle/trapi.py", line 100, in <dictcomp>
2022-02-10T09:54:24-05:00     binding["id"]: message.knowledge_graph.nodes[binding["id"]]
2022-02-10T09:54:24-05:00 TypeError: 'NodeBinding' object is not subscriptable

[chris-mondo-gene-small.json.txt](https://github.com/ranking-agent/strider/files/8042514/chris-mondo-gene-small.json.txt)

**Comment by uhbrar** [comment]
Is this happening in the deployed version? Running locally doesn't cause any crashes for me.

**Comment by PhillipsOwen** [comment]
it is happening on version v3.17.0.

**Comment by PhillipsOwen** [comment]
it is happening on the renci/k8s dev instance.
